server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 172.18.0.2
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Documents/SideProject/ProjectPractice/PracticeProject/MSA-practice/native-file-repo
        git:
          uri: file:///Users/ysjang/Documents/SideProject/ProjectPractice/PracticeProject/MSA-practice/git-local-repo

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,beans,httptrace,busrefresh