server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///Users/ysjang/Documents/SideProject/ProjectPractice/PracticeProject/MSA-practice/git-local-repo
